# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
PROJECT_ID = hybrid-cloud-rocks
FRONTEND_DOMAIN := hcr.k8s.io

CLUSTER_VERSION = 1.5.2
CLUSTER_REGIONS = us-central1 europe-west1 asia-east1
CLUSTER_MACHINE_TYPE = n1-standard-2
CLUSTER_ZONES = c
CLUSTER_NUM_NODES_PER_ZONE = 2
CLUSTER_SCOPES = https://www.googleapis.com/auth/cloud-platform
CLUSTER_IMAGE_TYPE = GCI

LOADERS_CLUSTER_NAME = gcp-loaders
LOADERS_CLUSTER_ZONE = us-central1-c
LOADERS_CLUSTER_MACHINE_TYPE = n1-standard-32
LOADERS_CLUSTER_NUM_NODES = 2
LOADERS_CLUSTER_SCOPES := $(CLUSTER_SCOPES)
LOADERS_CLUSTER_IMAGE_TYPE := $(CLUSTER_IMAGE_TYPE)

FEDERATION_CLUSTER_REGION = us-central1
FEDERATION_DOMAIN = hybrid-cloud-rocks.com
FEDERATION_NAME = hybrid-cloud-rocks
FEDERATION_CONTEXT := $(FEDERATION_NAME)

primary-vars:
	$(eval primary_cluster_region := $(firstword $(CLUSTER_REGIONS)))
	$(eval primary_cluster_name := gcp-$(primary_cluster_region))
	$(eval primary_cluster_zones := $(addprefix $(primary_cluster_region)-,$(CLUSTER_ZONES)))
	$(eval primary_cluster_zone := $(firstword $(primary_cluster_zones)))
	$(eval primary_cluster_context := gke_$(PROJECT_ID)_$(primary_cluster_zone)_$(primary_cluster_name))

%-vars:
	$(eval cluster_region := $(@:-vars=))
	$(eval cluster_name := gcp-$(cluster_region))
	$(eval cluster_zones := $(addprefix $(cluster_region)-,$(CLUSTER_ZONES)))
	$(eval cluster_zone := $(firstword $(cluster_zones)))
	$(eval more_zones := $(filter-out $(cluster_zone),$(cluster_zones)))
	$(eval cluster_context := gke_$(PROJECT_ID)_$(cluster_zone)_$(cluster_name))
ifneq ($(words $(CLUSTER_ZONES)),1)
	$(eval additional_zones := $(subst $(space),$(comma),$(more_zones)))
	$(eval additional_zones_flag := --additional-zones $(additional_zones))
endif
